# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
      - echo "Using pre-built HTML files"
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp -r docs/* $READTHEDOCS_OUTPUT/html/

      - mkdir --parents $READTHEDOCS_OUTPUT/pdf/
      - cp docs/_static/euromodconnector.pdf $READTHEDOCS_OUTPUT/pdf/euromodconnector.pdf
      #- cp docs/_static/euromodconnector.pdf _readthedocs/pdf/euromodconnector.pdf

# Optionally build your docs in additional formats such as PDF and ePub
formats:
   - pdf
   - epub
