baseURL: https://opensource.twitter.dev/
languageCode: en-us
title: Python Connector Euromod

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    style: friendly

menu:
  main:
  # individual pages are added to menu in their front matter
  - identifier: github
    name: GitHub
    url: https://github.com/iribelousova/PythonConnectorEuromod/
    weight: 20
